version: '3.8'
volumes:
  postgres-volume:
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: clients
      POSTGRES_USER: clients
      POSTGRES_DB: clients